Public Enum AccountSummaryValue
    AccountType
    NetLiquidation
    TotalCashValue
    SettledCash
    AccruedCash
    BuyingPower
    EquityWithLoanValue
    PreviousDayEquityWithLoanValue
    GrossPositionValue
    ReqTEquity
    ReqTMargin
    SMA
    InitMarginReq
    MaintMarginReq
    AvailableFunds
    ExcessLiquidity
    Cushion
    FullInitMarginReq
    FullMaintMarginReq
    FullAvailableFunds
    FullExcessLiquidity
    LookAheadNextChange
    LookAheadInitMarginReq
    LookAheadMaintMarginReq
    LookAheadAvailableFunds
    LookAheadExcessLiquidity
    HighestSeverity
    DayTradesRemaining
    Leverage
End Enum
